= VPRO Shared modules
:toc:

//image:https://travis-ci.com/vpro/vpro-shared.svg[BuildStatus,link=https://travis-ci.com/vpro/vpro-shared]
image:https://github.com/vpro/vpro-shared/workflows/build/badge.svg?[Build Status,link=https://github.com/vpro/vpro-shared/actions?query=workflow%3Abuild]
image:https://img.shields.io/maven-central/v/nl.vpro.shared/vpro-shared-parent.svg[MavenCentral,link=https://search.maven.org/search?q=g:%22nl.vpro.shared%22]
image:http://www.javadoc.io/badge/nl.vpro.shared/vpro-shared-parent.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/nl.vpro.shared]
image:https://codecov.io/gh/vpro/vpro-shared/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/vpro/vpro-shared]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/nl.vpro.shared/vpro-shared-parent.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/shared/]

These are various shared utility modules which are used on several
places in VPRO artifacts.

== highlights

* link:vpro-shared-util[vpro-shared-util]: Classes in `nl.vpro.util`. Related to collections and other low level java utilities.
* link:vpro-shared-logging[vpro-shared-logging]: Utilities related to logging. Mostly related to SLF4j. Also contains a more simple framework 'SimpleLogger', which is easy to implement on the fly
* link:archived/vpro-shared-elasticsearch7[vpro-shared-elasticsearch7]: Related to elasticsearch7 (archived)
* link:vpro-shared-elasticsearch-client[vpro-shared-elasticsearch-client]: Related to elasticsearch low level client
* link:vpro-shared-elasticsearch-high-level-client[vpro-shared-elasticsearch-high-level-client]: Related to elasticsearch high level client
* link:vpro-shared-swagger3[vpro-shared-swagger3]: Some utilities related to swagger frontend and openapi. Depends on webjars to provide the actuall swagger frontend too

* link:vpro-shared-monitoring[vpro-shared-monitoring]: Kind of like spring-actuator, for non-springboot applications. Providing the monitoring endpoints which can be used by openshift for example.
* link:archived/vpro-shared-couchdb-util[vpro-shared-couchdb-util]: Lightweight and streaming couchdb clients
* link:archived/vpro-shared-swagger[vpro-shared-swagger]: Some utilities related to swagger frontend. Depends on webjars.

 r frontend. Depends on webjars.
* ..

== Builds

SNAPSHOT builds can be found at https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/shared/

Release builds will be provided via https://search.maven.org/search?q=g:nl.vpro.shared[maven central].

== TODO

* Some of these modules are old, contain very little usefull or are very specific for VPRO. We should remove them.
* A bit more of documentation here and there would be welcome. Though we provide this mainly to be able to provide _other_ artifact too, which themselves depend on this
* Some, or perhaps even most or all, of the submodules should be migrated to git repositories of their own. They don't change often. This will make the builds faster and leaner.


== Version history


|===
|Major |remarks |

| 0/1.x
| lived at subversion @ vpro
| 2008 - 2018

| 2.x
| First version at github, java 8
| september 2018

| 3.x
| java 11
| november 2022

| 4.x
| java 17
| june 2023

| 4.3-SNAPHOT
| This is the branch for javax compatiblity. From this minor release can/will be made. Possible it can be merged to 4.4 if needed
  This would be done manually, since release branches are normally made from main
| February 2024


| 5.x
| javax -> jakarta
| February 2024

| 5.1
| hibernate orm 6, hibernate search 7
| May 2024

| 5.4
|
| January 2025


| 6.x >
| java 21 (released in sep. 2023)
| 2025?


|===

