= VPRO Shared modules

image:https://travis-ci.org/vpro/vpro-shared.svg[BuildStatus,link=https://travis-ci.org/vpro/vpro-shared]
image:https://img.shields.io/maven-central/v/nl.vpro.shared/vpro-shared-parent.svg?label=Maven%20Central[MavenCentral,link=https://search.maven.org/search?q=g:%22nl.vpro.shared%22]
image:http://www.javadoc.io/badge/nl.vpro.shared/vpro-shared-parent.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/nl.vpro.shared/vpro-shared-parent]
image:https://codecov.io/gh/vpro/vpro-shared/branch/master/graph/badge.svg[codecov,link=https://codecov.io/gh/vpro/vpro-shared]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/nl.vpro.shared/vpro-shared-parent.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/shared/]

These are various shared utility modules which are used on several
places in VPRO artifacts.

== highlights

* link:vpro-shared-util[vpro-shared-util]: Classes in `nl.vpro.util`. Related to collections and other low level java utilities.
* link:vpro-shared-logging[vpro-shared-logging]: Utilities related to logging. Mostly related to SLF4j. Also contains a more simple framework 'SimpleLogger', which is easy to implement on the fly
* link:vpro-shared-elasticsearch7[vpro-shared-eleasticsearch7]: Related to elasticsearch7
* link:vpro-shared-elasticsearch-client[vpro-shared-eleasticsearch-client]: Related to elasticsearch
* link:vpro-shared-couchdb-util[vpro-shared-couchdb-util]: Lightweight and streaming couchdb clients
* link:vpro-shared-swagger[vpro-shared-swagger]: Some utilities related to swagger frontend. Depends on webjars.
* ..

== Builds

SNAPSHOT builds can be found at https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/shared/

Release builds will be provided via https://search.maven.org/search?q=g:nl.vpro.shared[maven central].

== TODO

* Some of these modules are old, contain very little usefull or are very specific for VPRO. We should remove them.
* A bit more of documentation here and there would be welcome. Though we provide this mainly to be able to provide _other_ artifact too, which themselves depend on this
* Some, or perhaps even most or all, of the submodules should be migrated to git repositories of their own. They don't change often. This will make the builds faster and leaner.
