
= Shared utilities
:toc:

image:http://www.javadoc.io/badge/nl.vpro.shared/vpro-shared-util.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/nl.vpro.shared/vpro-shared-util]

Simple utilities with little or no dependencies themselves

E.g.
- Collection related, like CountedIterator, ClosableIterator, SkippingIterator, TransformingList, BatchedReceiver
- Strings related, like TextUtil, HTMLStripper, Strings
- JMX related: `nl.vpro.jmx`
- CommandExecutor to convientiently call external commands
- …

== CommandExecutor

[source,java]
----
 // initialize
 CommandExecutor convert = CommandExecutorImpl
                 .builder()
                 .executablesPaths("/opt/local/bin/convert", "/bin/convert", "/usr/local/bin/convert")
                 .commonArg("-")
                 .commonArg("png:-")
                 .logger(log)
                 .wrapLogInfo(CharSequence::toString)
                 .build();


  //use
  File out = File.createTempFile(FilenameUtils.removeExtension(pdfFileName), ".png");
  try (OutputStream outputStream = new FileOutputStream(out)) {
      int exitCode = convert.execute(zip, outputStream, LoggerOutputStream.error(log));
      if (exitCode != 0) {
           log.warn("Exit code: {}", exitCode);
      }
  }
----

== Batched Receiver

If an API provides access to huge set of elements, they often do it with some paging mechanism, or by some 'resumption token' formalism. With `nl.vpro.util.BatchedReceiver` this can be morphed into a simple `java.util.Iterator`.

=== Paging

The 'batchGetter' argument should be a `java.util.BiFunction`, returning an iterator for the page described by given offset and batch size

[source,java]
----
Iterator<String> i = BatchedReceiver.<String>builder()
    .batchGetter((offset, max) ->
       apiClient.getPage(offset, max).iterator()
    )
    .batchSize(6)
    .build();
i.forEachRemaining(string -> {
      ...<do stuff...>
  });
----

=== Resumption token

You simply provide a `java.util.Supplier`. A lambda would probably not suffice because you might need the previous result the get the next one. E.g. this (using https://olingo.apache.org/doc/odata4/index.html[olingo] code)

[source,java]
----
   public Iterator<ClientEntity> iterate(URIBuilder ub) {
        return BatchedReceiver.<ClientEntity>builder()
            .batchGetter(new Supplier<Iterator<ClientEntity>>() {
                ClientEntitySet result;
                @Override
                public Iterator<ClientEntity> get() {
                    if (result != null) {
                        result = query(result.getNext());
                    } else {
                        result = query(ub);
                    }
                    return result.getEntities().iterator();
                }
            })
            .build();
    }
----

== Configuration utility

At vpro we use to place configuration properties file for all project on similar places.

The can be obtained like this:

[source,java]
----
nl.vpro.util.ConfigUtils#getPropertiesInHome("<my config file>.properties");
----

Resolves properties in class path and `user.home`/conf in a standardized way.

We also support a convention to have properties differ per OTAP environment

[source,java]
----
  Map<String, String> properties =
        ConfigUtils.filtered(env, ConfigUtils.getPropertiesInHome("openskosrepository.properties"));
----

It is also possible to instantiate objects using reflection.

[source,java]
----
TODO device examples
----

== JMX calls

The nl.vpro.jmx package contains a few utilities that we use when implementation JMX operations.

E.g.
[source, java]
----

@ManagedOperation
public String publishMediaChangedBackwards(long max) {
    return MBeans2.returnMultilineString( "backwards", () -> {
        log.info("a slow piece of code !");
    });
}
----

Will start up the 'slow piece of code'. After (on default) 5 seconds, it will leave that code running, but return what it logged until now (plus in indication that is not ready yet)

`backwards` is just a key. If the operation is called when it is still running it will refuse to do so. It can be `null` or omitted.

