
= Monitoring


Related to monitoring.

This basically adds endpoints:

[source]
----
/manage/health
/manage/metrics
----

to a spring application.

Normally just taking the dependency should suffice. It can be configured with spring properties (`monitoring.*`, see link:src/main/java/nl/vpro/monitoring/config/MonitoringProperties.java[`MonitoringProperties`]).

All have defaults, or can be set via system properties (such as for example the username/password for the monitoring endpoint)

Used in several spring openshift applications.


== Changes in 5.7

=== BEFORE
In versions prior to 5.7, there were also the following required changes in web.xml:

[source,xml]
.fragments from web.xml
----
<servlet>
    <servlet-name>manage</servlet-name>
    <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
    <load-on-startup>3</load-on-startup>
</servlet>

<servlet-mapping>
  <servlet-name>manage</servlet-name>
 <url-pattern>/manage/*</url-pattern>
</servlet-mapping>

----
And a `monitoring-context.xml` like this:
[source,xml]
----
<?xml version="1.0" ?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.springframework.org/schema/context https://www.springframework.org/schema/context/spring-context.xsd">

  <context:annotation-config/>

  <bean class="nl.vpro.monitoring.endpoints.MonitoringEndpoints"/>

</beans>

----
=== AFTER

It can be much simpler now, because newer servlet versions support 'web-fragment' files, which can be used to add servlets and filters without the need for a web.xml.
[source,xml]
.fragments from web.xml
----

 <absolute-ordering>
     <!-- other fragments -->
    <name>monitoring_endpoints</name>
  </absolute-ordering>
----
And even that is optional. The required changes to the servlet environment are then arranged in vpro-shared-monitoring.jar itself.

Not that this does require the jar to be included in 'jarsToScan' of tomcat. That defaults to all jars, but to speed up start up times it is recommended to limit it, but this one should be included then.   The ghcr.io/vpro/tomcat is ok in version >= 10.26

This will set up spring to serve out the `/manage/*` endpoints. Since 5.7 it will also try to serve out `/.well-known/security.txt` (which will be filled with the file /well-known/security.txt).

For `/manage/metrics` to work, you also need a `MeterRegistry` in the spring context.  This can be done, with `@EnabledMonitoring` on a configuration class, or otherwise registering a `MeterRegistry` bean. It should be in the root the root context. This endpoint is also protected with basic security. The default name password is admin/admin2k, but this can be set by spring properties or environment variables.

Since 5.12 all endpoints are handled by the `ManageFilter` rather than different servlets. Because as it turns out, some  spring applications just map `/\*` to the DispatcherServlet, and then that hides the servlets from the web fragments. This is circumvented this way, the filter also matches everything, and just chains everything it can't handle. An extra advantage is that the ManageFilter can also be configured to use other paths. E.g. if you prefer `/manage/health` can also be set to `/health` or `/admin/health` or whatever you like. See `monitoring.endpoints.*` properties.
