name: create release branch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-
      if: always()
    - uses: oleksiyrudenko/gha-git-credentials@v2.1
      with:
        global: true
        name: 'github'
        email: 'digitaal-techniek@vpro.nl'
        token: '${{ secrets.GITHUB_TOKEN  }}'
    - name: Release branch with Maven
      run: mvn --batch-mode release:branch


