name: build

on:
  push:
    branches: [ master, "REL-*" ]

  workflow_dispatch:
    inputs:
      skipTests:
        description: 'Skip tests'
        required: true
        default: 'false'

env:
  skipTests: false

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
    - uses: getong/elasticsearch-action@v1.2
      with:
        elasticsearch version: '7.6.1'
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clean settings.xml
      run: rm -rf ~/.m2/settings.xml
    - name: Create settings.xml
      uses: s4u/maven-settings-action@v1
      with:
        servers: '[{"id": "vpro-ossrh", "username": "vpro", "password": "${{secrets.SONATYPE_PASSWORD}}"}, {"id": "gpg.passphrase", "passphrase": "${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}"}]'
    -
      name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
    - name: Build with Maven
      run: mvn -fae -DskipITs=false -DskipTests=${skipTests} -Dinteg.cluster.name=docker-elasticsearch -B -Pdeploy,sonatype deploy  -Dgpg.skip=false
    - name: Publish to codecov
      run: bash <(curl -s https://codecov.io/bash)
      continue-on-error: true
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: always()
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
