---
name: release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/REL-')
    permissions:
      contents: write
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - name: echo
        run: echo {{ $github.ref }}
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_USERNAME
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          cache: maven
      - uses: oleksiyrudenko/gha-git-credentials@v2.1.2
        with:
          global: true
          name: 'github'
          email: 'digitaal-techniek@vpro.nl'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release
        run: mvn  -Pdeploy --batch-mode  -Darguments=-DskipTests  release:prepare release:perform
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
